### ISSUE TITLE
Can you add a New Carrier: DPD in for Europe?

### ISSUE THREAD

**Issue by mmougin** [jkeen/tracking_number_data#37]
We are using this code with success for many of the carriers included. However, we have run into another carrier that is popular in Europe.

Dynamic Parcel Distribution (DPD) is the second largest company in the parcel and express logistics sector in Germany, second only to Deutsche Post subsidiary DHL. The company is a subsidiary of GeoPost S.A., an international parcel and logistics provider owned by French company La Poste.

https://www.dpd.com/tracking

In some googling this might be helpful
https://www.trackingmore.com/tracking-status-detail-en-259.html

Is it possible to get new carriers added? and whats the process for that? Not sure how active this project is.

**Comment by jkeen** [comment]
Yeah, the project stagnated a bit--there's lots of usage but not much in terms of contributions and it's fallen off my radar lately but have been meaning to get back and address some of these issues, and mainly I wanted to make it easier to troubleshoot/contribute to this project.

I welcome PRs. It's just a matter of defining the definition of this number in this library. The trickiest part that people tend to overlook when wanting to add numbers is that in order to best verify a number we have to know the algorithm to verify the check digit. Tracking numbers without check digits make it hard to accurately identify the numbers. 

Are you using this with the ruby gem?

**Comment by rjswenson** [comment]
Hello jkeen, I'm in the same org as mmougin above.  We do use the ruby gem to populate shipping carrier and then send that information to our frontend.  I do understand adding an additional carrier is a pain if we don't have the exact algorithm.  Otherwise there may be collisions when checking what carrier a specific shipping number belongs to.  We of course appreciate any enhancements you do make and will work on a PR if it seems this effort is something we want to move forward with.

**Comment by jkeen** [comment]
@rjswenson @mmougin Thanks for the info. I've added two different types of DPD numbers that I found docs for, but the ones you linked on trackingmore I can not find or figure out any details about 🤷🏻‍♂️ 

Everything I found about what DPD themselves report about their own tracking numbers has been added though
